# Generated by Django 2.2.15 on 2020-08-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.BigIntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
